/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import modele.metier.Salarie;
import java.text.SimpleDateFormat;  
import java.util.Date; 

/**
 *
 * @author lucie
 */
public class JDialogUnSalarie extends javax.swing.JDialog {

        private Salarie salarieAAfficher = null;

    public JDialogUnSalarie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDateNaiss = new javax.swing.JTextField();
        jLabelTauxHoraire = new javax.swing.JLabel();
        jTextFieldDateEmbauche = new javax.swing.JTextField();
        jLabelSituationFamiliale = new javax.swing.JLabel();
        jTextFieldFonction = new javax.swing.JTextField();
        jLabelNbrEnfants = new javax.swing.JLabel();
        jTextFieldTauxHoraire = new javax.swing.JTextField();
        jTextFieldSituationFamiliale = new javax.swing.JTextField();
        jTextFieldNbrEnfants = new javax.swing.JTextField();
        jLabelNomService = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jTextFieldNomService = new javax.swing.JTextField();
        jLabelPrenom = new javax.swing.JLabel();
        jTextFieldLibelle = new javax.swing.JTextField();
        jLabelDateNaiss = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabelLibelle = new javax.swing.JLabel();
        jLabelDateEmbauche = new javax.swing.JLabel();
        jTextFieldPrenom = new javax.swing.JTextField();
        jLabelFonction = new javax.swing.JLabel();
        jButtonRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fiche salarié");

        jTextFieldDateNaiss.setEditable(false);

        jLabelTauxHoraire.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTauxHoraire.setText("Taux horaire :");

        jTextFieldDateEmbauche.setEditable(false);
        jTextFieldDateEmbauche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateEmbaucheActionPerformed(evt);
            }
        });

        jLabelSituationFamiliale.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSituationFamiliale.setText("Situation familiale :");

        jTextFieldFonction.setEditable(false);
        jTextFieldFonction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFonctionActionPerformed(evt);
            }
        });

        jLabelNbrEnfants.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNbrEnfants.setText("Nombre d'enfants :");

        jTextFieldTauxHoraire.setEditable(false);

        jTextFieldSituationFamiliale.setEditable(false);

        jTextFieldNbrEnfants.setEditable(false);
        jTextFieldNbrEnfants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNbrEnfantsActionPerformed(evt);
            }
        });

        jLabelNomService.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNomService.setText("Service :");

        jLabelNom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNom.setText("Nom :");

        jTextFieldNomService.setEditable(false);

        jLabelPrenom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrenom.setText("Prénom :");

        jTextFieldLibelle.setEditable(false);

        jLabelDateNaiss.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDateNaiss.setText("Date de naissance :");

        jTextFieldNom.setEditable(false);
        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });

        jLabelLibelle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLibelle.setText("Grade :");

        jLabelDateEmbauche.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDateEmbauche.setText("Date d'embauche :");

        jTextFieldPrenom.setEditable(false);

        jLabelFonction.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFonction.setText("Fonction :");

        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFonction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLibelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTauxHoraire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelSituationFamiliale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNbrEnfants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldFonction)
                            .addComponent(jTextFieldTauxHoraire)
                            .addComponent(jTextFieldSituationFamiliale)
                            .addComponent(jTextFieldLibelle)
                            .addComponent(jTextFieldNbrEnfants, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDateNaiss, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jLabelDateEmbauche, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNomService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNomService, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldDateEmbauche, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRetour)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDateNaiss))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDateEmbauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDateEmbauche))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomService)
                    .addComponent(jTextFieldNomService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLibelle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFonction)
                    .addComponent(jTextFieldFonction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldTauxHoraire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelTauxHoraire, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSituationFamiliale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSituationFamiliale))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbrEnfants)
                    .addComponent(jTextFieldNbrEnfants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonRetour)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDateEmbaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateEmbaucheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateEmbaucheActionPerformed

    private void jTextFieldFonctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFonctionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFonctionActionPerformed

    private void jTextFieldNbrEnfantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNbrEnfantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNbrEnfantsActionPerformed

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogUnSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogUnSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogUnSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogUnSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogUnSalarie dialog = new JDialogUnSalarie(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void afficherSalarie(){
        if (salarieAAfficher != null){
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
            
            jTextFieldNom.setText(salarieAAfficher.getNom());
            jTextFieldPrenom.setText(salarieAAfficher.getPrenom());
            jTextFieldFonction.setText(salarieAAfficher.getFonction());
            jTextFieldSituationFamiliale.setText(salarieAAfficher.getSituationFamiliale());
            jTextFieldNbrEnfants.setText(String.valueOf(salarieAAfficher.getNbrEnfants()));
            jTextFieldTauxHoraire.setText(String.valueOf(salarieAAfficher.getTauxHoraire()));
            jTextFieldDateNaiss.setText(String.valueOf(formatter.format(salarieAAfficher.getDateNaiss())));
            jTextFieldDateEmbauche.setText(String.valueOf(formatter.format(salarieAAfficher.getDateEmbauche())));
            jTextFieldLibelle.setText(String.valueOf(salarieAAfficher.getCategorie().getLibelle()));
            jTextFieldNomService.setText(String.valueOf(salarieAAfficher.getService().getDesignation()));
        }
    }
    
    public void setSalarieAAfficher (Salarie salarieAAfficher){
        this.salarieAAfficher = salarieAAfficher;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JLabel jLabelDateEmbauche;
    private javax.swing.JLabel jLabelDateNaiss;
    private javax.swing.JLabel jLabelFonction;
    private javax.swing.JLabel jLabelLibelle;
    private javax.swing.JLabel jLabelNbrEnfants;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNomService;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelSituationFamiliale;
    private javax.swing.JLabel jLabelTauxHoraire;
    private javax.swing.JTextField jTextFieldDateEmbauche;
    private javax.swing.JTextField jTextFieldDateNaiss;
    private javax.swing.JTextField jTextFieldFonction;
    private javax.swing.JTextField jTextFieldLibelle;
    private javax.swing.JTextField jTextFieldNbrEnfants;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldNomService;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldSituationFamiliale;
    private javax.swing.JTextField jTextFieldTauxHoraire;
    // End of variables declaration//GEN-END:variables
}
