/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import modele.dao.ConnexionBDD;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author lucie
 */
public class JDialogAjoutSalarie extends javax.swing.JDialog {

    Connection cnx = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    
    /**
     * Creates new form JDialogAjoutSalarie
     */
    public JDialogAjoutSalarie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    JDialogAjoutSalarie() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldEnfant = new javax.swing.JTextField();
        jTextFieldFamille = new javax.swing.JTextField();
        jTextFieldService = new javax.swing.JTextField();
        jButtonValider = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jLabelPrenom = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabelDateEmbauche = new javax.swing.JLabel();
        jComboBoxCat = new javax.swing.JComboBox<>();
        jLabelLibCat1 = new javax.swing.JLabel();
        jLabelFonction = new javax.swing.JLabel();
        jLabelTauxHoraire = new javax.swing.JLabel();
        jLabelSituationFamiliale = new javax.swing.JLabel();
        jLabelNbrEnfants = new javax.swing.JLabel();
        jLabelNbrEnfants2 = new javax.swing.JLabel();
        jLabelNbrEnfants3 = new javax.swing.JLabel();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldGrade = new javax.swing.JTextField();
        jTextFieldTH = new javax.swing.JTextField();
        jTextFieldFonction = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajouter un salarié");

        jTextFieldEnfant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnfantActionPerformed(evt);
            }
        });

        jTextFieldFamille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFamilleActionPerformed(evt);
            }
        });

        jTextFieldService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldServiceActionPerformed(evt);
            }
        });

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        jLabel2.setText("Code");

        jLabelNom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNom.setText("Nom :");
        jLabelNom.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTextFieldCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeActionPerformed(evt);
            }
        });

        jLabelPrenom.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrenom.setText("Prenom :");
        jLabelPrenom.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Date de naissance :");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabelDateEmbauche.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDateEmbauche.setText("Date d'embauche :");
        jLabelDateEmbauche.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jComboBoxCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C1", "C2", "E1", "E2" }));

        jLabelLibCat1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLibCat1.setText("Grade :");
        jLabelLibCat1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabelFonction.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFonction.setText("Fonction :");
        jLabelFonction.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabelTauxHoraire.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTauxHoraire.setText("Taux horaire :");
        jLabelTauxHoraire.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabelSituationFamiliale.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSituationFamiliale.setText("Situation familiale :");
        jLabelSituationFamiliale.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabelNbrEnfants.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNbrEnfants.setText("Nombre d'enfants :");
        jLabelNbrEnfants.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabelNbrEnfants2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNbrEnfants2.setText("Service :");
        jLabelNbrEnfants2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabelNbrEnfants3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNbrEnfants3.setText("Categorie :");
        jLabelNbrEnfants3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTextFieldPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomActionPerformed(evt);
            }
        });

        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });

        jTextFieldGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGradeActionPerformed(evt);
            }
        });

        jTextFieldTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTHActionPerformed(evt);
            }
        });

        jTextFieldFonction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFonctionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDateEmbauche, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSituationFamiliale)
                    .addComponent(jLabelNbrEnfants3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNbrEnfants2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNbrEnfants)
                    .addComponent(jLabelTauxHoraire, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFonction, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLibCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFonction, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldService, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEnfant, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jButtonRetour)
                    .addGap(44, 44, 44)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addComponent(jButtonValider))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCode, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jTextFieldFamille, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(38, 38, 38)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNom)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrenom))
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabelDateEmbauche)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLibCat1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFonction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFonction))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTauxHoraire))
                .addGap(19, 19, 19)
                .addComponent(jLabelSituationFamiliale)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEnfant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNbrEnfants))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNbrEnfants2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNbrEnfants3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(49, 49, 49)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(128, 128, 128)
                    .addComponent(jTextFieldFamille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonValider)
                        .addComponent(jButtonRetour))
                    .addGap(18, 18, 18)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEnfantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnfantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnfantActionPerformed

    private void jTextFieldFamilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFamilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFamilleActionPerformed

    private void jTextFieldServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldServiceActionPerformed

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        try{
            String requete = "insert into salarie (Code,Nom,Prenom,DateNaiss,DateEmbauche,Fonction,TauxHoraire,situationFamiliale,NbrEnfants,NumCat,CodeServ) values (?,?,?,?,?,?,?,?,?,?,?)";
            cnx = ConnexionBDD.getConnexion();
            pstmt = cnx.prepareStatement(requete);

            pstmt.setString(1,jTextFieldCode.getText());
            pstmt.setString(2,jTextFieldNom.getText());
            pstmt.setString(3,jTextFieldPrenom.getText());

            pstmt.setDate(4,convertUtilToSql(jDateChooser1.getDate()));

            pstmt.setDate(5,convertUtilToSql(jDateChooser2.getDate()));

            pstmt.setString(6,jTextFieldFonction.getText());
            pstmt.setString(7,jTextFieldTH.getText());
            pstmt.setString(8,jTextFieldFamille.getText());
            pstmt.setString(9,jTextFieldEnfant.getText());
            pstmt.setString(10, (String) jComboBoxCat.getSelectedItem());
            pstmt.setString(11,jTextFieldService.getText());

            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(null, "saved");

        }catch(Exception e){
            System.out.println("SQLException: "+e);
        }finally{
            try{
                pstmt.close();
                rs.close();
            }catch(Exception e){

            }
        }

    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonRetourActionPerformed

    private void jTextFieldCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodeActionPerformed

    private void jTextFieldPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomActionPerformed

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jTextFieldGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGradeActionPerformed

    private void jTextFieldTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTHActionPerformed

    private void jTextFieldFonctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFonctionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFonctionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAjoutSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAjoutSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAjoutSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAjoutSalarie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogAjoutSalarie dialog = new JDialogAjoutSalarie(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JComboBox<String> jComboBoxCat;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDateEmbauche;
    private javax.swing.JLabel jLabelFonction;
    private javax.swing.JLabel jLabelLibCat1;
    private javax.swing.JLabel jLabelNbrEnfants;
    private javax.swing.JLabel jLabelNbrEnfants2;
    private javax.swing.JLabel jLabelNbrEnfants3;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelSituationFamiliale;
    private javax.swing.JLabel jLabelTauxHoraire;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldEnfant;
    private javax.swing.JTextField jTextFieldFamille;
    private javax.swing.JTextField jTextFieldFonction;
    private javax.swing.JTextField jTextFieldGrade;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldService;
    private javax.swing.JTextField jTextFieldTH;
    // End of variables declaration//GEN-END:variables

    private Date convertUtilToSql(java.util.Date date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
