/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modele.dao.ConnexionBDD;
import modele.dao.DaoSalarie;
import modele.dao.DaoService;
import modele.metier.Salarie;
import modele.metier.Service;
/**
 *
 * @author lucie
 */
public class JFrameUnService extends javax.swing.JFrame {

    DefaultListModel modeleListeSalarie;
    DefaultComboBoxModel modeleListeService;
    Connection cnx = ConnexionBDD.getConnexion();
    /**
     * Creates new form JFrameUnService
     */
    public JFrameUnService() throws SQLException, IOException {
        initComponents();
        modeleListeSalarie = new DefaultListModel();
        modeleListeService = new DefaultComboBoxModel();
        jComboBoxServices.setModel(modeleListeService);
        jListLesSalaries.setModel(modeleListeSalarie);

        afficherService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListLesSalaries = new javax.swing.JList<>();
        jLabelListeSalaries = new javax.swing.JLabel();
        jComboBoxServices = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonConsulter = new javax.swing.JButton();
        jButtonAjouter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnSupprimer1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fiche services");

        jListLesSalaries.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Salarié 1", "Salarié 2", "Salarié 3", "Salarié 4", "Salarié 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListLesSalaries);

        jLabelListeSalaries.setText("Liste des salariés du service :");

        jComboBoxServices.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tous les services", "Comptabilité", "Technique", "Informatique", "Gestion" }));
        jComboBoxServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServicesActionPerformed(evt);
            }
        });

        jLabel1.setText("Services :");

        jButtonConsulter.setText("Consulter");
        jButtonConsulter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConsulterMouseClicked(evt);
            }
        });

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnSupprimer1.setText("Modifier");
        btnSupprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelListeSalaries, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxServices, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnSupprimer1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSupprimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAjouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsulter))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabelListeSalaries)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsulter)
                    .addComponent(jButtonAjouter)
                    .addComponent(btnSupprimer)
                    .addComponent(btnSupprimer1))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServicesActionPerformed
        
    int indiceElementCourant = jComboBoxServices.getSelectedIndex();
    
    String srvChoisi = jComboBoxServices.getItemAt(indiceElementCourant);
    
        try {
            afficherSalarie(srvChoisi);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameUnService.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBoxServicesActionPerformed

    private void jButtonConsulterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsulterMouseClicked
    int indiceElementCourant = jListLesSalaries.getSelectedIndex();
        Salarie salCourant = (Salarie) modeleListeSalarie.getElementAt(indiceElementCourant);

        JDialogUnSalarie jDialogUnSalarie = new JDialogUnSalarie(this, true);
        jDialogUnSalarie.setLocation(this.getX()+100,this.getY()+100);
        jDialogUnSalarie.setSalarieAAfficher(salCourant);// fournir le salarié à afficher
        jDialogUnSalarie.afficherSalarie();       // remplir les champs de la fenêtre avec les valeurs
        jDialogUnSalarie.setVisible(true);       // afficherSalrie la fenêtre        
    }//GEN-LAST:event_jButtonConsulterMouseClicked

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        JDialogAjoutSalarie jf = new JDialogAjoutSalarie();
        jf.setVisible(true);
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
       
        int indiceElementCourant = jListLesSalaries.getSelectedIndex();
        Salarie salCourant = (Salarie) modeleListeSalarie.getElementAt(indiceElementCourant);
        int choix=JOptionPane.showConfirmDialog(this,"Vous voulez", "confirm", JOptionPane.OK_CANCEL_OPTION);
        
        
       

        if (choix==0){
                
                    
                            String code=salCourant.getCode();
                            System.out.print(code);
            try {
                DaoSalarie.supprimerSalarie(code);
            } catch (SQLException | IOException ex) {
                Logger.getLogger(JFrameUnService.class.getName()).log(Level.SEVERE, null, ex);
            }
                            
                        
                
                    
        }
        this.dispose();
        
       
       
       
       
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnSupprimer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupprimer1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new JFrameUnService().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JFrameUnService.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(JFrameUnService.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void afficherService() throws SQLException, IOException{
        jComboBoxServices.addItem("Tout les services");
        for (Service srv : DaoService.getAll()) {
                jComboBoxServices.addItem(srv.getDesignation());
            }
        
        
    }
     public void afficherSalarie(String srvChoisi) throws SQLException{
        
        modeleListeSalarie.clear();
        try {
            //Si tout les services veulent être affiché.
            if (srvChoisi.equals("Tout les services")){
                
                for (Salarie sal : DaoSalarie.getAll()){
                    modeleListeSalarie.addElement(sal);
                }
                
            }else{
                //Si on veut afficher uniquement un service.
                for (Salarie sal : DaoSalarie.getAll()) {
                
                    if(sal.getService().getDesignation().equals(srvChoisi)){
                        
                    modeleListeSalarie.addElement(sal);
                    
                    }
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(JFrameUnService.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnSupprimer1;
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonConsulter;
    private javax.swing.JComboBox<String> jComboBoxServices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelListeSalaries;
    private javax.swing.JList<String> jListLesSalaries;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}